require('dotenv').config();
const fs = require('fs');
const path = require('path');

const buildFile = path.join(__dirname, '..', 'main.3951cf1b.js');
const configFile = path.join(__dirname, '..', 'public', 'mth-config.js');
const apiBase = (process.env.API_PUBLIC_URL || process.env.API_BASE_URL || 'http://localhost:5000').replace(/\/$/, '');

let content = fs.readFileSync(buildFile, 'utf8');

// Dynamic API URL — reads from window.MTH_API_BASE (set in mth-config.js)
const dynamicFetch =
  'fetch((window.MTH_API_BASE||"' + apiBase + '")+"/api/registration",r)';

const patterns = [
  /fetch\("https?:\/\/[^"]+\/api\/registration",r\)/,
  /fetch\(\(window\.MTH_API_BASE\|\|"[^"]*"\)\+"\/api\/registration",r\)/,
];

let replaced = false;
for (const pattern of patterns) {
  if (pattern.test(content)) {
    content = content.replace(pattern, dynamicFetch);
    replaced = true;
    break;
  }
}

if (!replaced) {
  console.error('Could not find registration fetch() in main.3951cf1b.js');
  process.exit(1);
}

fs.writeFileSync(buildFile, content);

fs.writeFileSync(
  configFile,
  `// Auto-generated by npm run patch-frontend\nwindow.MTH_API_BASE = '${apiBase}';\n`
);

console.log('Submit button connected to:', apiBase + '/api/registration');
console.log('Updated:', buildFile);
console.log('Updated:', configFile);
console.log('\nOn IONOS: add this BEFORE main.3951cf1b.js in your HTML:');
console.log('  <script src="https://YOUR-RENDER-URL/mth-config.js"></script>');
console.log('Or upload public/mth-config.js to IONOS and link it locally.');
